swagger: "2.0"
info:
  version: 1.0.0
  title: Image gallery api
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
- text/plain
paths:
  /albums:
    x-swagger-router-controller: albums
    get:
      description: Returns all albums meta definition from the gallery
      tags:
      - gallery
      operationId: getAlbums
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/AlbumsResponse.yaml
        401:
          description: User unauthorized
          schema:
            type: string
  /albums/{id}/images:
    x-swagger-router-controller: albums
    get:
      description: Returns album with all images
      tags:
      - gallery
      operationId: getImages
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Id of the album
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/ImagesResponse.yaml
        404:
          description: An album with given id was not found
  /login:
    x-swagger-router-controller: auth
    post:
      description: Logs user into the application
      tags:
      - auth
      operationId: login
      parameters:
        - name: LoginRequest
          in: body
          description: Login credentials
          schema:
            $ref: defs/Login.yaml
      responses:
        200:
          description: User authenticated
          schema:
            $ref: defs/User.yaml
        401:
          description: User unauthorized
          schema:
            type: string
  /user:
    x-swagger-router-controller: auth
    get:
      description: Logs user into the application
      tags:
      - auth
      operationId: getUser
      responses:
        200:
          description: User authenticated
          schema:
            $ref: defs/User.yaml
        401:
          description: User unauthorized
          schema:
            type: string
definitions:
  Album:
    $ref: defs/Album.yaml
  Image:
    $ref: defs/Image.yaml
  AlbumsResponse:
    $ref: defs/AlbumsResponse.yaml
  ImagesResponse:
    $ref: defs/ImagesResponse.yaml
  Login:
    $ref: defs/Login.yaml
  User:
    $ref: defs/User.yaml
