swagger: "2.0"
info:
  version: 1.0.0
  title: Photo gallery api
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /albums:
    x-swagger-router-controller: albums
    get:
      description: Returns all albums meta definition from the gallery
      tags:
      - gallery
      operationId: getAlbums
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/AlbumsResponse.yaml
  /albums/{id}:
    x-swagger-router-controller: albums
    get:
      description: Returns album with all photos
      tags:
      - gallery
      operationId: getAlbum
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/AlbumDetails.yaml
definitions:
  Album:
    $ref: defs/Album.yaml
  AlbumsResponse:
    $ref: defs/AlbumsResponse.yaml
  AlbumDetails:
    $ref: defs/AlbumDetails.yaml
  Photo:
    $ref: defs/Photo.yaml
