swagger: "2.0"
info:
  version: 1.0.0
  title: Image gallery api
basePath: /api
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /albums:
    x-swagger-router-controller: albums
    get:
      description: Returns all albums meta definition from the gallery
      tags:
      - gallery
      operationId: getAlbums
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/AlbumsResponse.yaml
  /albums/{id}/images:
    x-swagger-router-controller: albums
    get:
      description: Returns album with all images
      tags:
      - gallery
      operationId: getImages
      responses:
        200:
          description: offering created
          schema:
            $ref: defs/ImagesResponse.yaml
definitions:
  Album:
    $ref: defs/Album.yaml
  Image:
    $ref: defs/Image.yaml
  AlbumsResponse:
    $ref: defs/AlbumsResponse.yaml
  ImagesResponse:
    $ref: defs/ImagesResponse.yaml
